name: Lint Plugins

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run claudelint
        run: |
          docker run --rm -v $(pwd):/workspace ghcr.io/stbenjam/claudelint:main -v --strict
